version: '3'
# services:
#   nexus:
#     image: sonatype/nexus3
#     container_name: nexus
#     ports:
#       - "8081:8081"
#     volumes:
#       - /var/lib/docker/volumes/nexus-data:/nexus-data
#     environment:
#       - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g



services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
 
volumes:
  pgdata:

# services:
#   postgres:
#     image: postgres:latest
#     container_name: postgres_container
#     environment:
#       POSTGRES_USER: postgres_user
#       POSTGRES_PASSWORD: postgres_password
#       POSTGRES_DB: postgres_db
#       PGDATA: /vagrant/pgdata
#     ports:
#       - "5430:5432"
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data/pgdata
#     deploy:
#       resources:
#         limits:
#           cpus: '0.50'
#           memory: 512M
#         reservations:
#           cpus: '0.25'
#           memory: 256M
#     command: >
#       postgres -c max_connections=1000
#                -c shared_buffers=256MB
#                -c effective_cache_size=768MB
#                -c maintenance_work_mem=64MB
#                -c checkpoint_completion_target=0.7
#                -c wal_buffers=16MB
#                -c default_statist

# networks:
#   default:
#     external:
#       name: some-existing-network
